#!/bin/sh
. "$(dirname "$0")/husky.sh"

branch=$(git rev-parse --abbrev-ref HEAD)

if [ "$branch" = "main" ]; then
  echo "You're pushing to 'main'. Running checks...."

  echo "Running yarn prettier..."
  yarn prettier --check .
  if [ $? -ne 0 ]; then
    echo "Prettier failed. Aborting push."
    exit 1
  fi

  echo "Running yarn lint..."
  yarn lint
  if [ $? -ne 0 ]; then
    echo "Lint failed. Aborting push."
    exit 1
  fi

  echo "Running yarn test..."
  yarn test
  if [ $? -ne 0 ]; then
    echo "Tests failed. Aborting push."
    exit 1
  fi

  echo "All checks passed. Proceeding with push."
else
  echo "Not on 'main' branch (current: $branch). Skipping checks."
fi
