name: Build and deploy Nx app to Azure Web App - challenge-test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Clean Nx and remove old build
        run: |
          npx nx reset
          rm -rf dist/apps/challenge-test

      - name: Build Nx app
        run: npx nx run challenge-test:build

      - name: Copy server.js into build output
        run: |
          cp server.js dist/apps/challenge-test/
          echo "Copied server.js to build output"

      - name: List build directory
        run: ls -la dist/apps/challenge-test

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: dist/apps/challenge-test/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: deployment

      - name: Show deployment folder contents
        run: ls -la deployment

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_192857EBE98E46BC984040E2ACA92FDA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_85C039D845F04583A10F655A0C083F28 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A87F1E3B7664458CA8470F2C178B6236 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'challenge-test'
          slot-name: 'Production'
          package: deployment

      - name: Restart Azure Web App
        run: |
          az webapp restart --name challenge-test --resource-group challenge-test_group-a35b
